### ISSUE TITLE
Prevent the usage of aliases (OSOE-472)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/PowerShell-Analyzers#12]
Aliases like `?` instead of `Where-Object` or `%` instead of `ForEach-Object` hurt readability. They're fine as shortcuts if you're writing throwaway scripts, but once the script is shared in a team (as well as open-sourced) we should go the path of better readability with more verbose code.

I actually changed these aliases in our GitHub Actions repo here: https://github.com/Lombiq/GitHub-Actions/pull/101/files

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-472)

**Comment by BenedekFarkas** [comment]
I've already updated [Utility Scripts](https://github.com/Lombiq/Utility-Scripts) in https://github.com/Lombiq/Utility-Scripts/pull/26 before we discussed this, and [Infrastructure Scripts](https://github.com/Lombiq/Infrastructure-Scripts) didn't have any to begin with. Need to check if there are other repos affected.

**Comment by sarahelsaig** [comment]
Using the same logic we should also abandon `$_` in favor of `$PSItem` for example. (yet afaik there is no analyzer rule for that) `%` and `?` are well known enough that anyone who knows PS at all should recognize them and they are stylistically coherent with using `$_`.

**Comment by Piedone** [comment]
I'd do `PSItem` as well.

**Comment by sarahelsaig** [comment]
Then I suggest expanding the issue's scope to [create a custom rule](https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/create-custom-rule?view=ps-modules) for `$PSItem`. I remain not a fan of this issue (because I don't think making the most common and well-known PS functions unnecessarily wordy actually helps readability), but I am a fan of enforcing consistency.

**Comment by Piedone** [comment]
Yep!

**Comment by BenedekFarkas** [comment]
Yeah, that sounds reasonable. I'm using `$_` everywhere in Infrastructure Scripts, so you caught me red-handed with that. :D
