### ISSUE TITLE
Enable further analyzer rules for better code styling control and more (OSOE-501)

### ISSUE THREAD

**Issue by BenedekFarkas** [Lombiq/PowerShell-Analyzers#16]
Review https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/rules/readme and out of the ones that aren't enabled by default, select the appropriate ones. Repositories to check: OSOCE, Infrastructure Scripts, Utility Scripts.

[Complete list](https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/rules/readme?view=ps-modules):

1. ✅[PSAlignAssignmentStatement](https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/rules/alignassignmentstatement?view=ps-modules): The authors recommend this for readability (I like it better too) and it's easy to fix and maintain in VS Code with just one setting. Moved to #21.
2. ✅[PSAvoidLongLines](https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/rules/avoidlonglines?view=ps-modules): For C#, we have guidelines (vertical ruler) for 120 and 140 characters and have a hard limit at 150, so 150 here would be nice. We have 72 violations overall at the 150 limit. Moved to #23.
3. ✔️[PSAvoidSemicolonsAsLineTerminators](https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/rules/avoidsemicolonsaslineterminators?view=ps-modules): This is super simple but requires update to 1.21.0 (doesn't seem to be any breaking changes so far).
4. ✔️[PSAvoidUsingDoubleQuotesForConstantString](https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/rules/avoidusingdoublequotesforconstantstring?view=ps-modules): Consistency! VS Code could auto-fix this if `powerShell.codeFormatting.useConstantStrings` is enabled. We're currently only surfacing Warnings and Errors (but not Information entries). This rule has Information severity, but the docs is outdated on that, so I created an issue and PR: https://github.com/MicrosoftDocs/PowerShell-Docs-Modules/issues/128
We can lower the threshold (I'd actually rather move it to the settings file from Invoke-Analyzers.ps1) to Information and then disable the rules that we don't care about but enabled by default (there are only 2 such possible rules).
6. ✔️[PSPlaceCloseBrace](https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/rules/placeclosebrace?view=ps-modules)
7. ✔️[PSPlaceOpenBrace](https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/rules/readme?view=ps-modules)
8. ⛔[PSUseCompatibleCommands](https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/rules/usecompatiblecommands?view=ps-modules): Skip (at least I don't see its usefulness at the moment).
9. ⛔[PSUseCompatibleSyntax](https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/rules/usecompatiblesyntax?view=ps-modules): I don't think we need this, because we run analysis on both the latest Windows PowerShell and PowerShell Core, so incompatible syntax is already surfaced by runtime errors.
10. ⛔[PSUseCompatibleTypes](https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/rules/usecompatibletypes?view=ps-modules): Probably not interesting now.
11. ✔️[PSUseConsistentIndentation](https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/rules/useconsistentindentation?view=ps-modules): Definitely useful!
12. ✔️[UseConsistentWhitespace](https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/rules/useconsistentwhitespace?view=ps-modules): Definitely useful!
13. ✔️[PSUseCorrectCasing](https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/rules/usecorrectcasing?view=ps-modules): Also great for consistency. ~Not yet enabled because of https://github.com/PowerShell/PSScriptAnalyzer/issues/1881. Moved to #22.~

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-501)

**Comment by BenedekFarkas** [comment]
When `PSUseConsistentWhitespace.CheckParameter` is `$true`, [this code from Wait-SqlServer](https://github.com/Lombiq/GitHub-Actions/blob/2d0cb9683dd7e71ebb88fcd9eaf3ad9c0c78b077/.github/actions/setup-sql-server/Wait-SqlServer.ps1#L9) generates two warnings:
```powershell
if ($Env:RUNNER_OS -eq "Windows")
{
    sqlcmd -b -S .\SQLEXPRESS -Q "SELECT @@SERVERNAME as ServerName" 2>&1>$null
}
else
{
    sqlcmd -b -U sa -P 'Password1!' -Q "SELECT @@SERVERNAME as ServerName" 2>&1>$null
}
```

VSCode autoformatting changes this to the following, making the warnings go away, but I don't think this is correct:
```powershell
if ($Env:RUNNER_OS -eq "Windows")
{
    sqlcmd -b -S .\SQLEXPRESS -Q "SELECT @@SERVERNAME as ServerName" >$null
}
else
{
    sqlcmd -b -U sa -P 'Password1!' -Q "SELECT @@SERVERNAME as ServerName" >$null
}
```

@DAud-IcI do you know if we can just update this to save into a variable or something similar to instead of the "exotic" syntax?

**Comment by BenedekFarkas** [comment]
Also, when `PSUseCorrectCasing` is enabled, the error below is thrown locally because of [this exact line](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/blob/34fa7759ce89bf0d775640f20e31f342d3cc3e53/NuGetTest/Update-LombiqNuGetPackages.ps1#L1):
```powershell
Update-VisualStudioSolutionNuGetPackages -Path (Get-Location).Path -ProjectNameFilter "Lombiq.*" -PackageNameFilter "Lombiq.*"
```

```
Invoke-ScriptAnalyzer: [...]\tools\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell\Invoke-Analyzer.ps1:117
Line |
 117 |  … ch-Object { Invoke-ScriptAnalyzer -Path $PSItem.FullName @analyzerPar …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find an overload for ".ctor" and the argument count: "1".
```

Any ideas? GHA execution is fine though.

**Comment by sarahelsaig** [comment]
> do you know if we can just update this to save into a variable or something similar to instead of the "exotic" syntax?

mfw someone calls the stream redirection syntax that has been common in pretty much all shells since the dawn of time "exotic".

![image](https://user-images.githubusercontent.com/4007293/211828915-f9919620-09f3-40d9-a536-23f7733bdec6.png)

`2>&1` tells the shell to merge the standard error stream into the standard output stream on-the-fly. That's where `sqlcmd` outputs all the warnings. If for some reason we want to show SQL client warnings in the logs, then the reformatted version is ok. Otherwise for this scenario we could use `2>$null >$null` which is a more verbose equivalent. There you individually send each stream into [NUL](https://superuser.com/questions/134214/is-there-an-equivalent-to-dev-null-in-windows) instead of merging the two first.

-----

> Also, when PSUseCorrectCasing is enabled, the error below is thrown locally

It appears the script throws a PowerShell syntax error, it can't even be caught using try-catch.
![image](https://user-images.githubusercontent.com/4007293/211842890-44adb752-89a1-4b2f-8664-d1b06f007da5.png)

The reason it "works" in GHA is because it doesn't produce the error GHA expects.
![image](https://user-images.githubusercontent.com/4007293/211842336-fd8d05c7-5562-4d88-8ad0-ee1d5268b175.png)
(here contrast the raw error message with the neat GHA style errors caused by the sloppily formatted try-catch I added)

So I'm afraid the `PSUseCorrectCasing` is just broken? I'd avoid using it for the time being. Can you open an issue about this at PowerShell/PSScriptAnalyzer? I've isolated a minimal repro that can be used with just their module and vanilla pwsh:

 ```pwsh
'@{ Rules = @{ PSUseCorrectCasing = @{ Enable = $true } } }' > rules.psd1
Invoke-ScriptAnalyzer -Settings rules.psd1 -ScriptDefinition 'Update-VisualStudioSolutionNuGetPackages'
```

**Comment by BenedekFarkas** [comment]
> mfw someone calls the stream redirection syntax that has been common in pretty much all shells since the dawn of time "exotic".

Ha! :D
Well, I never had to use it, so I'm considering myself lucky, then!

---

> If for some reason we want to show SQL client warnings in the logs, then the reformatted version is ok.

So, the reformatted version doesn't break it and `$?` still captures the status of the command execution, right? Then we can just put ` | Out-Null` after it, so there won't be any visible output.

---

> So I'm afraid the PSUseCorrectCasing is just broken? I'd avoid using it for the time being. Can you open an issue about this at PowerShell/PSScriptAnalyzer? I've isolated a minimal repro that can be used with just their module and vanilla pwsh:

Thanks! The weird thing is that the original code doesn't violate PSUseCorrectCasing either and that analyzer works just fine otherwise.
See: https://github.com/PowerShell/PSScriptAnalyzer/issues/1881

**Comment by BenedekFarkas** [comment]
I don't know what the heck is going on with the `Update-VisualStudioSolutionNuGetPackages` string in PowerShell, but auto-formatting on in the `Update-LombiqNuGetPackages.ps1` doesn't work either (e.g., for fixing `PSAvoidUsingDoubleQuotesForConstantString` violations).
If I remove a single character from the `Update-VisualStudioSolutionNuGetPackages` cmdlet name (doesn't matter which one), then auto-formatting works again, and the error exhibited above also goes away...

**Comment by 0liver** [comment]
The second part of the commandlet name is currently 33 characters long - maybe **32** is a magical number here?! The name is quite long, admittedly.

Why does **VisualStudio** have to be part of it, anyway?

**Comment by BenedekFarkas** [comment]
I noticed that too, but we have cmdlets with longer names, e.g., `Remove-AzureWebAppSqlDatabaseContainedUser`.
`Update-VisualStudioSolutionNuGetPackages` and one of the underlying cmdlets are specifically reading information from VS solutions (they are a wrapper for the `dotnet sln` command).

**Comment by BenedekFarkas** [comment]
I factored out 3 analyzers to separate issue (see them marked with ✅ in the description), so this is done.

**Comment by 0liver** [comment]
A very wise decision, let me tell you!

**Comment by BenedekFarkas** [comment]
Check this out! https://github.com/PowerShell/PSScriptAnalyzer/issues/1881#issuecomment-1387354660

`PSUseCorrectCasing` is now also enabled.
