### ISSUE TITLE
Add GHA action/workflow to run PS analysis (OSOE-504)

### ISSUE THREAD

**Issue by BenedekFarkas** [Lombiq/PowerShell-Analyzers#17]
So that it doesn't have to be a submodule to be able to use it.
Include configuration options to run Windows PowerShell and/or PowerShell Core.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-504)

**Comment by Piedone** [comment]
This will necessitate a change to the `static-code-analysis` workflows in Infrastructure Scripts and PowerShell Analyzers too. See https://github.com/Lombiq/Utility-Scripts/pull/28#discussion_r1052640912 for context.
