### ISSUE TITLE
PSReviewUnusedParameter in-place suppression instead of disabling the rule (OSOE-528)

### ISSUE THREAD

**Issue by BenedekFarkas** [Lombiq/PowerShell-Analyzers#18]
The `PSReviewUnusedParameter` is disabled in our current configuration, because it produces false positives when a parameter is only used in a local function, but not in the main script body. See https://github.com/PowerShell/PSScriptAnalyzer/issues/1472.

A recent comment (https://github.com/PowerShell/PSScriptAnalyzer/issues/1472#issuecomment-1372431462) tipped me off to try suppressing those cases in-place, so we can re-enable the rule.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-528)

**Comment by Piedone** [comment]
Shouldn't we instead wait for the bug to be fixed? In your PRs I see only suppressions, but no change due to the rule finding an issue. So, while it may catch issues in the future, apparently we don't have those frequently, and now it only necessitates suppressing false alarms.

**Comment by BenedekFarkas** [comment]
The issue has been open for 2 and a half years, so why should we wait more?
There were a handful of true positives I fixed during one of the previous issues.

**Comment by Piedone** [comment]
This rule currently brings more suppressions than fixes. So I don't see why we'd use it, especially since the bugs it guards against are minor.

**Comment by Piedone** [comment]
@DAud-IcI please see this discussion.

**Comment by sarahelsaig** [comment]
Ah, I reviewed this a few hours earlier but then took a nap because the merging seemed complex. Shouldn't have slacked if I knew it leaves time for discussion. 😁
Anyway, it's pretty inconsequential either way, since only 2 scripts had to be suppressed.

**Comment by Piedone** [comment]
![image](https://user-images.githubusercontent.com/1976647/211417524-bd097a36-2565-41eb-8b92-adff99d621c5.png)
