### ISSUE TITLE
Custom analyzer rule for parameter and variable name styling (OSOE-580)

### ISSUE THREAD

**Issue by BenedekFarkas** [Lombiq/PowerShell-Analyzers#31]
Origin: https://github.com/Lombiq/GitHub-Actions/pull/197#discussion_r1115710863

Implement it along the lines of [Measure-AutomaticVariableAlias](https://github.com/Lombiq/PowerShell-Analyzers/blob/dev/Lombiq.Analyzers.PowerShell/Rules/Measure-AutomaticVariableAlias/Measure-AutomaticVariableAlias.psm1), which analyses variable names.

1. [Parameter names](https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.language.parametertoken) should be alphanumeric-only AND start with an uppercase letter. 
2. [Variable names](https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.language.variabletoken) should be alphanumeric-only AND start with a lowercase letter.

In both cases, check if automatic suggestions can be applied to fix these, but only if they're not functionally breaking:
1. Removing non-alphanumeric characters should be consistent across the whole file.
2. Correcting the casing of the first character of a parameter/variable might cause a collision.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-580)

**Comment by BenedekFarkas** [comment]
The original discussion mentions local variables specifically, but we should include parameters too (maybe in a separate rule) without the "lowercase first letter" restriction unless that causes incompatibility with something.

**Comment by sarahelsaig** [comment]
Good point. In parameters we should have an uppercase first letter restriction instead.

**Comment by BenedekFarkas** [comment]
That's right, description updated!

**Comment by BenedekFarkas** [comment]
Looked into this and combed through [the available tokens](https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.language.tokenkind), but neither of the above seem feasible:

1. Parameter names aren't a separate token in the sense we discussed above, because they are also just variables, so we can't validate their casing without a very complicated analysis of the rest of function by manually separating function parameters from local variables. The Param token would help with that, but then the logic would also need to find the immediate next LParen and RParent tokens and process what's between them and then detect the function parameters.
2. Instead, Parameter tokens are the ones appearing when calling a function, e.g., `-ErrorAction` in `Get-Process $Name -ErrorAction SilentlyContinue`. These are already validated by `PSUseCorrectCasing`, although it doesn't check that it starts with an uppercase character, rather that it matches the casing defined in the called function's Param block, but I'd leave it at that.

**Comment by BenedekFarkas** [comment]
@sarahelsaig what do you think of the above comment?

**Comment by sarahelsaig** [comment]
Looking for parentheses after a `Param` token seems feasible to me. The `param` keyword has to be at the very start of the script (excluding comments) so if we find the first `RParen` sibling after it, then we can use that point to split the syntax tree in half. Any variable name before it goes into the list of parameter names, any variable after is checked against the list.

**Comment by BenedekFarkas** [comment]
I'm not sure how to access syntax tree, we only get a list of the tokens. But your comment made me realize that if the list of tokens is in order, then it's a lot easier than I initially thought, so I'll look into that.

**Comment by sarahelsaig** [comment]
Ah, I assumed you are using [System.Management.Automation.Language.Parser]::ParseFile which returns an abstract syntax tree. btw check this out:
![image](https://github.com/Lombiq/PowerShell-Analyzers/assets/4007293/81a8078e-318e-4a50-a2b0-f041e45831fa)

**Comment by BenedekFarkas** [comment]
You were right though, an analyzer can receive the AST too as a parameter: https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/create-custom-rule#each-function-must-have-a-token-array-or-an-ast-parameter

I'll check if this simplifies things, but I already have a complete implementation that iterates through the whole list of tokens just once and it can handle multiple functions in the same file (but not embedded functions). I imagine a lot of different cases would still need to be handled when inspecting the AST too, but we'll see.
