### ISSUE TITLE
Analyzer violations don't show files and lines when run in GitHub Actions (OSOE-875)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/PowerShell-Analyzers#43]
See e.g. [this run](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/9768426280/job/26965899107), only the errors are shown:

![image](https://github.com/Lombiq/PowerShell-Analyzers/assets/1976647/0ae6e60f-6830-4358-97db-be2c57ff01ac)

This makes finding and fixing them harder.

The issue might be similar to https://github.com/Lombiq/GitHub-Actions/issues/365: These annotations seem to be broken for good if `file` is specified (I couldn't find a way to make them work: https://github.com/Lombiq/GitHub-Actions/issues/365#issuecomment-2204507259). So, the solution can be just changing [this line](https://github.com/Lombiq/PowerShell-Analyzers/blob/11fc2d3d645292a2d1c1fba285f4d9eebefc6f79/Lombiq.Analyzers.PowerShell/Invoke-Analyzer.ps1#L52) to `Write-Output "::error::$Message"`.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-875)

**Comment by sarahelsaig** [comment]
I'd try something like
```pwsh
Write-Output "::error$(if ($Path) { " title=$Path (Line: $Line; Column: $Column)::$Message" } else { "::$Message" })"
```
or
```pwsh
Write-Output "::error::$Message $(if ($Path) { "(Path: $Path; Line: $Line; Column: $Column)" })"
```
because `Write-Output "::error::$Message"` will only output exactly as much as you already see on the screenshot.

**Comment by Piedone** [comment]
Yeah indeed, `$Message` is not enough, so we should go with your second suggestion. I tried `title` before for https://github.com/Lombiq/GitHub-Actions/issues/365 and it didn't work either, but we can see if maybe it'll do something here.

**Comment by Piedone** [comment]
Yeah, error annotation titles still don't work: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/9780958471/job/27003865573?pr=804
